apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lab-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
      - name: lab
        image:  gcr.io/galunches-193923/lab:$LAB_VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: URL
            value: "https://accret.io"
          - name: ELASTICSEARCH_ENDPOINT
            value: "elasticsearch"
          - name: MIXPANEL_TOKEN
            value: $MIXPANEL_TOKEN
  
