apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lab-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
      - name: lab
        image:  gcr.io/accretio-180222/lab:0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: URL
            value: "https://accret.io"
          - name: ELASTICSEARCH_ENDPOINT
            value: "elasticsearch"
          - name: MIXPANEL_TOKEN
            value: "6221bafa38007f6f95fb31da88456141"
  
